# Generated by Django 2.1.5 on 2020-04-01 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_original_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='productType',
            field=models.CharField(choices=[('D', 'Desktops'), ('L', 'Laptops'), ('P', 'Printers'), ('O', 'Peripherals'), ('A', 'Apple Products'), ('C', 'CCTV Cameras')], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
